FROM node:16-alpine

ENV SRCDIR /app
RUN mkdir -p $SRCDIR && chown -R node:node $SRCDIR

# Add custom environment to pass in development server
ENV PATH $SRCDIR/node_modules/.bin:$PATH

WORKDIR $SRCDIR
COPY ./package.json .

RUN yarn cache clean && yarn --verbose

COPY . .

EXPOSE 3000