FROM node:16-alpine

# Use this SRCDIR if you want to use nginx-proxy, edit VIRTUAL_ROOT in env/local.env
# ENV SRCDIR /var/www/public/react.localhost 

ENV SRCDIR /app

# Add custom environment to pass in local development
ENV PATH $SRCDIR/node_modules/.bin:$PATH
RUN mkdir -p $SRCDIR && chown -R node:node $SRCDIR

WORKDIR $SRCDIR

COPY package.json .
RUN yarn --verbose
COPY . .

EXPOSE 3001

CMD ["yarn", "start"]